base {
    log_debug = off;
    log_info = off;
    //log = "file:/var/log/redsocks.log";
    daemon = on;
    redirector = iptables;
}
 
redsocks {
    local_ip = 0.0.0.0;
    local_port = 8123;
 
    ip = 127.0.0.1;
    port = 2323;
    //Если есть авторизация
    //login = "";
    //password = "";
    type = socks5;
}

