#!/bin/bash

_TorNet()
{
  _script_commands="gui_vpn gui_tor start_tor start_vpn stop_tor gui_proxy proxy_tor status speedtest gui"

  local cur
  COMPREPLY=()
  cur="${COMP_WORDS[COMP_CWORD]}"
  COMPREPLY=( $(compgen -W "${_script_commands}" -- ${cur}) )

  return 0
}
complete -o nospace -F _TorNet TorNet

