#!/bin/bash

_TorNet()
{
  _script_commands="start_tor start_vpn stop_tor proxy_tor status speedtest gui stop_vpn https_proxy http_proxy socks5_proxy"

  local cur
  COMPREPLY=()
  cur="${COMP_WORDS[COMP_CWORD]}"
  COMPREPLY=( $(compgen -W "${_script_commands}" -- ${cur}) )

  return 0
}
complete -o nospace -F _TorNet TorNet

